### ISSUE TITLE
LanguageUtils是否会考虑增加获取之前已设置的语言类型的方法

### ISSUE THREAD

**Issue by showdy** [Blankj/AndroidUtilCode#1108]
请问，LanguageUtils是否会考虑增加获取之前已设置的语言类型的方法

**Comment by Blankj** [comment]
getCurrentLocale 不就是么

**Comment by Kolbrezev92** [comment]
Breze Wolfe has sent you an email via Gmail confidential mode:

[image: Gmail logo]Re: [Blankj/AndroidUtilCode] LanguageUtils是否会考虑增加获取之前已设置的语言类型的方法 (#1108) <https://confidential-mail.google.com/msg/ABTZP1w9yUARGRnCr1z9_Af193NdkLSKfpsaCkUr7uTbx4jIVWBV1cew1C0H87HLVKgqAF4SgzZbUzvAObx7GWLCkGcOgvPuAVi70PShlfZBwEkTVnuOeZdaJk5OylsWzWWkNLNIHmkjbdJZKq1RLTa-JcRFxlm7ULsMQjh9YY1_IqrulH89kKyPhn9xRJog38e-YfejZl1EwBw=>

This message was sent on Dec 5, 2019 at 8:47:13 PM PST
You can open it by clicking the link below. This link will only work for reply@reply.github.com.

View the email <https://confidential-mail.google.com/msg/ABTZP1w9yUARGRnCr1z9_Af193NdkLSKfpsaCkUr7uTbx4jIVWBV1cew1C0H87HLVKgqAF4SgzZbUzvAObx7GWLCkGcOgvPuAVi70PShlfZBwEkTVnuOeZdaJk5OylsWzWWkNLNIHmkjbdJZKq1RLTa-JcRFxlm7ULsMQjh9YY1_IqrulH89kKyPhn9xRJog38e-YfejZl1EwBw=>

Gmail confidential mode gives you more control over the messages you send. The sender may have chosen to set an expiration time, disable printing or forwarding, or track access to this message. Learn more <https://support.google.com/mail/answer/7674059>
Gmail: Email by Google
Use is subject to the Google Privacy Policy <https://myaccount.google.com/privacypolicy?hl=en>
Google LLC, 1600 Amphitheatre Parkway, Mountain View, CA 94043, USA
You have received this message because someone sent you an email via Gmail confidential mode.
[image: Google logo]

**Comment by Kolbrezev92** [comment]
U304AA-user 9 P00610 1582809540 release-keys
